In [13]:
import polars as pl

In [14]:
workforce_df = pl.read_csv("../datasets/cleaned/all_workforce_cleaned.csv")
capacity_df = pl.read_csv("../datasets/cleaned/all_capacity_cleaned.csv")

In [15]:
workforce_df.head(5)

shape: (5, 5)
┌──────┬────────────────────────┬───────────────────────────┬───────┬──────┐
│ year ┆ sector                 ┆ specialist_non-specialist ┆ count ┆ type │
│ ---  ┆ ---                    ┆ ---                       ┆ ---   ┆ ---  │
│ i64  ┆ str                    ┆ str                       ┆ i64   ┆ str  │
╞══════╪════════════════════════╪═══════════════════════════╪═══════╪══════╡
│ 2006 ┆ Public                 ┆ na                        ┆ 3505  ┆      │
│ 2006 ┆ Private                ┆ na                        ┆ 2966  ┆      │
│ 2006 ┆ Not In Active Practice ┆ na                        ┆ 460   ┆      │
│ 2007 ┆ Public                 ┆ na                        ┆ 3991  ┆      │
│ 2007 ┆ Private                ┆ na                        ┆ 3004  ┆      │
└──────┴────────────────────────┴───────────────────────────┴───────┴──────┘

In [16]:
capacity_df.head(5)

shape: (5, 8)
┌──────┬──────────────┬──────────────┬──────────────┬─────────────┬─────────┬────────┬─────────────┐
│ year ┆ institution_ ┆ facility_typ ┆ public_priva ┆ no_of_facil ┆ no_beds ┆ sector ┆ facility_ty │
│ ---  ┆ type         ┆ e_a          ┆ te           ┆ ities       ┆ ---     ┆ ---    ┆ pe_b        │
│ i64  ┆ ---          ┆ ---          ┆ ---          ┆ ---         ┆ i64     ┆ str    ┆ ---         │
│      ┆ str          ┆ str          ┆ str          ┆ i64         ┆         ┆        ┆ str         │
╞══════╪══════════════╪══════════════╪══════════════╪═════════════╪═════════╪════════╪═════════════╡
│ 2009 ┆ Hospital     ┆ Acute        ┆ Public       ┆ 7           ┆ 6416    ┆        ┆             │
│ 2009 ┆ Hospital     ┆ Acute        ┆ Not-for-Prof ┆ 1           ┆ 303     ┆        ┆             │
│      ┆              ┆              ┆ it           ┆             ┆         ┆        ┆             │
│ 2009 ┆ Hospital     ┆ Acute        ┆ Private      ┆ 6           ┆ 1570    ┆        ┆             │
│ 2009 ┆ Hospital     ┆ Psychiatric  ┆ Public       ┆ 1           ┆ 2040    ┆        ┆             │
│      ┆              ┆ Hospitals    ┆              ┆             ┆         ┆        ┆             │
│ 2009 ┆ Hospital     ┆ Psychiatric  ┆ Not-for-Prof ┆ 0           ┆ 0       ┆        ┆             │
│      ┆              ┆ Hospitals    ┆ it           ┆             ┆         ┆        ┆             │
└──────┴──────────────┴──────────────┴──────────────┴─────────────┴─────────┴────────┴─────────────┘

In [17]:
import matplotlib.pyplot as plt
import seaborn as sns

def bar_graph(df:pl.DataFrame, x: str, y: str, hue : str= None, title: str = None):
    plt.figure(figsize=(10, 6))
    sns.barplot(data=df.to_pandas(), x=x, y=y, hue=hue)
    plt.title(title)
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

In [18]:
bar_graph(workforce_df, "sector", "count", None, "Workforce Distribution by Sector")

ModuleNotFoundError: pa.Table requires 'pyarrow' module to be installed